#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl --system stop    aloha.service >/dev/null 2>&1 || true
            systemctl --system disable aloha.service >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#
